### ISSUE TITLE
Bug: Invoking `svg2png` 600~700 times in a row causes a crash

### ISSUE THREAD

**Issue by CrasherX** [FHPythonUtils/NoCairoSVG#1]
### System info

- OS: Windows 10 21H2 19044.1466
- Python: '3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]'
- NoCairoSVG: 2022

### Describe the bug
I am trying to convert a large amount of files, putting `svg2png` in a loop. After about 650 files, the program hangs. I tried multiple times, always the same outcome (only difference is the number of files varies a little bit, but not much); tried with different files as well, same result. Interestingly, upon hanging, it also causes short lags in other, unrelated software I have running 🤔.

```
svg2png(url="input_%d.svg" % idx, write_to="output_%d.png" % idx)
```

### Expected outcome
All files converted.

### Actual outcome
Only about 650 converted.

Sometimes I get this error:
```
Traceback (most recent call last):
  File "C:\foo\main.py", line 148, in <module>
    main(n_images)
  File "C:\foo\main.py", line 142, in main
    process_png(num_images)
  File "C:\foo\main.py", line 129, in process_png
    svg2png(url="input_%d.svg" % idx, write_to="output_%d.png" % idx)
  File "C:\foo\venv\lib\site-packages\nocairosvg\__init__.py", line 108, in svg2png
    return svg2bitmap(
  File "C:\foo\venv\lib\site-packages\nocairosvg\__init__.py", line 345, in svg2bitmap
    image = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\foo\venv\lib\site-packages\nocairosvg\__init__.py", line 443, in convert
    img = Image.open(BytesIO(base64.b64decode(png_dat)))
  File "C:\foo\venv\lib\site-packages\PIL\Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E5735CAEA0>
```

Sometimes instead of hanging it crashes with this:
![image](https://user-images.githubusercontent.com/19915365/151676255-f0815010-1f94-41e4-8d2e-a15e6ad725bd.png)
```
Traceback (most recent call last):
  File "C:\foo\main.py", line 148, in <module>
    main(n_images)
  File "C:\foo\main.py", line 142, in main
    process_png(num_images)
  File "C:\foo\main.py", line 129, in process_png
    svg2png(url="input_%d.svg" % idx, write_to="output_%d.png" % idx)
  File "C:\foo\venv\lib\site-packages\nocairosvg\__init__.py", line 108, in svg2png
    return svg2bitmap(
  File "C:\foo\venv\lib\site-packages\nocairosvg\__init__.py", line 345, in svg2bitmap
    image = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\foo\venv\lib\site-packages\nocairosvg\__init__.py", line 429, in convert
    browser = await launch(
  File "C:\foo\venv\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\foo\venv\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\foo\venv\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\foo\venv\lib\site-packages\pyppeteer\launcher.py", line 219, in killChrome
    self._cleanup_tmp_user_data_dir()
  File "C:\foo\venv\lib\site-packages\pyppeteer\launcher.py", line 134, in _cleanup_tmp_user_data_dir
    raise IOError('Unable to remove Temporary User Data')
OSError: Unable to remove Temporary User Data
```

**Comment by FredHappyface** [comment]
Looks like chrome itself hangs - not sure why. Though I'm going to guess its because it is opened and closed 700 times 


This is the block of code that triggers the error:

site-packages\pyppeteer\launcher.py", line 222: get_ws_endpoint
```py
def get_ws_endpoint(url) -> str:
    url = url + '/json/version'
    timeout = time.time() + 30
    while (True):
        if time.time() > timeout:
            raise BrowserError('Browser closed unexpectedly:\n')
        try:
            with urlopen(url) as f:
                data = json.loads(f.read().decode())
            break
        except (URLError, HTTPException):
            pass
        time.sleep(0.1)

    return data['webSocketDebuggerUrl']
```

Might be worth raising the issue there but be aware that launching chrome 700 times in a row will not be expected use of the api. Other solutions might involve throttling the frequency that you call the converter on your end?

**Comment by CrasherX** [comment]
Makes sense.
Is there any way to re-use a single instance?

**Comment by FredHappyface** [comment]
Not really that I can see. Tried creating a global browser variable and ensuring that I close tabs and the browser after use. Testing even 100 converts resulted in a crash for me 

I will update what I've got as this should help with the resource leak
